import OR.Adequacy
import OR.Sieber.Reinterpret

/-!
# Müller's grade-1 game terms

F. Müller, *On Berry's conjectures about the stable order in PCF*, LMCS 8(4), 2012.

* Definition 3.1: a *finite term of grade `i`* is a closed `M` with `M ≅ Ψᵢ M`, where
  `Ψ^ι_i = λx. if x then 0 else if pre¹ x then 1 else … if preⁱ x then i else ⊥` and
  `Ψ^{σ→τ}_i = λf. λx. Ψ^τ_i (f (Ψ^σ_i x))`.
* Definition 4.1: game terms are generated by `⊥^σ`, `λx⃗. m` and
  `λx⃗. caseᵢ (y M⃗) N₀ … Nᵢ`; those of grade `i` use only `caseᵢ` and constants `≤ i`.
  `caseᵢ M N₀ … Nᵢ` is the macro `if M then N₀ else if pre¹ M then N₁ else … ⊥`.
* Theorem 4.12 (with `M = N`, `i = j`): every finite term `M` of grade `i` satisfies
  `M ≅ gtᵢ(M)` for a game term `gtᵢ(M)` of grade `i`.

This file transcribes the grade-1 case into this repository's PCF (`MullerPsi`, `Game`,
`MullerGameTermTheorem`), reading Müller's `pre`, `if`, `Y`, numerals and `⊥^σ` as
`pred`, `ifz`, `fix`, `succⁿ 0` and `Tm.omega σ`.  The grammar `Game` contains every
grade-1 game term (it also allows `λ` over `⊥`, which only weakens the hypothesis).

It then proves, using the Kripke full abstraction theorem of this repository, that the
transcribed statement implies `MullerGrade1`: `MullerPsi` is equivalent to
`projectionTerm · 1`, and every game term is equivalent to `embed` of a Boolean term.
-/

set_option autoImplicit false

noncomputable section

namespace OR.Sieber

/-! ## The terms -/

/-- Müller's `Ψ₁`. -/
def MullerPsi : (τ : OR.Ty) → OR.Tm [] (τ ⇒ τ)
  | .nat => .lam (case1 (.var .vz) .zero (.succ .zero))
  | .arr σ τ =>
      .lam (.lam (.app (OR.Tm.closed (MullerPsi τ))
        (.app (.var (.vs .vz)) (.app (OR.Tm.closed (MullerPsi σ)) (.var .vz)))))

mutual
/-- Grade-1 game terms, indexed by Boolean types (`B` read as `nat`). -/
inductive Game : Ctx → Ty → Type where
  | bot {Γ : Ctx} {τ : Ty} : Game Γ τ
  | lam {Γ : Ctx} {σ τ : Ty} : Game (σ :: Γ) τ → Game Γ (σ ⇒ τ)
  /-- The constant `0` (`false`) or `1` (`true`). -/
  | num {Γ : Ctx} : Bool → Game Γ .B
  /-- `case₁ (y M⃗) N₀ N₁`. -/
  | case {Γ : Ctx} : Spine Γ .B → Game Γ .B → Game Γ .B → Game Γ .B

/-- A variable applied to game terms. -/
inductive Spine : Ctx → Ty → Type where
  | var {Γ : Ctx} {τ : Ty} : Var Γ τ → Spine Γ τ
  | app {Γ : Ctx} {σ τ : Ty} : Spine Γ (σ ⇒ τ) → Game Γ σ → Spine Γ τ
end

mutual
def Game.toTm : {Γ : Ctx} → {τ : Ty} → Game Γ τ → OR.Tm (natCtx Γ) (natTy τ)
  | _, τ, .bot => OR.Tm.omega (natTy τ)
  | _, _, .lam G => .lam G.toTm
  | _, _, .num false => .zero
  | _, _, .num true => .succ .zero
  | _, _, .case s n0 n1 => case1 s.toTm n0.toTm n1.toTm

def Spine.toTm : {Γ : Ctx} → {τ : Ty} → Spine Γ τ → OR.Tm (natCtx Γ) (natTy τ)
  | _, _, .var x => .var (natVar x)
  | _, _, .app s G => .app s.toTm G.toTm
end

/-- `λx⃗. ⊥` at a Boolean type. -/
def botAt {Γ : Ctx} : (τ : Ty) → Tm Γ τ
  | .B => .bot
  | .arr _ ρ => .lam (botAt ρ)

mutual
/-- The Boolean reading `Gᴮ` of a game term. -/
def Game.toBool : {Γ : Ctx} → {τ : Ty} → Game Γ τ → Tm Γ τ
  | _, τ, .bot => botAt τ
  | _, _, .lam G => .lam G.toBool
  | _, _, .num false => .tt
  | _, _, .num true => .ff
  | _, _, .case s n0 n1 => .ite s.toBool n0.toBool n1.toBool

def Spine.toBool : {Γ : Ctx} → {τ : Ty} → Spine Γ τ → Tm Γ τ
  | _, _, .var x => .var x
  | _, _, .app s G => .app s.toBool G.toBool
end

/-! ## Denotations in the Kripke model -/

theorem denote_embed_botAt : ∀ {Γ : Ctx} (τ : Ty) (ρ : OR.Env (natCtx Γ)),
    OR.denote (embed (botAt (Γ := Γ) τ)) ρ = ⊥
  | _, .B, ρ => OR.denote_omega _ ρ
  | Γ, .arr σ τ, ρ => by
      apply OR.Hom.ext
      intro a
      exact denote_embed_botAt (Γ := σ :: Γ) τ (ρ, a)

mutual
theorem Game.denote_toTm : ∀ {Γ : Ctx} {τ : Ty} (G : Game Γ τ) (ρ : OR.Env (natCtx Γ)),
    OR.denote G.toTm ρ = OR.denote (embed G.toBool) ρ
  | _, τ, .bot, ρ => by
      change OR.denote (OR.Tm.omega (natTy τ)) ρ = OR.denote (embed (botAt τ)) ρ
      rw [OR.denote_omega, denote_embed_botAt]
  | _, _, .lam G, ρ => by
      apply OR.Hom.ext
      intro a
      exact G.denote_toTm (ρ, a)
  | _, _, .num false, _ => rfl
  | _, _, .num true, _ => rfl
  | _, _, .case s n0 n1, ρ => by
      change OR.denote (case1 s.toTm n0.toTm n1.toTm) ρ =
        OR.denote (case1 (embed s.toBool) (embed n0.toBool) (embed n1.toBool)) ρ
      simp only [case1, OR.denote_ifz, OR.denote_pred, s.denote_toTm, n0.denote_toTm,
        n1.denote_toTm]

theorem Spine.denote_toTm : ∀ {Γ : Ctx} {τ : Ty} (s : Spine Γ τ) (ρ : OR.Env (natCtx Γ)),
    OR.denote s.toTm ρ = OR.denote (embed s.toBool) ρ
  | _, _, .var _, _ => by simp only [Spine.toTm, Spine.toBool, embed]
  | _, _, .app s G, ρ => by
      simp only [Spine.toTm, Spine.toBool, embed, OR.denote_app]
      rw [s.denote_toTm, G.denote_toTm]
end

/-- Every closed game term is observationally equivalent to the embedding of its
Boolean reading. -/
theorem Game.equiv_embed {τ : Ty} (G : Game [] τ) : ContextualOpEq G.toTm (embed G.toBool) :=
  (OR.full_abstraction_op_eq _ _).mpr (OR.Hom.ext fun ρ => G.denote_toTm ρ)

theorem denote_MullerPsi : ∀ τ : OR.Ty, OR.denoteClosed (MullerPsi τ) = OR.projection τ 1
  | .nat => by
      apply OR.Hom.ext
      intro d
      rw [OR.projection_nat]
      rcases d with _ | _ | _ | k
      · rfl
      · rfl
      · rfl
      · simp [MullerPsi, case1, OR.Ground.cut]
        rfl
  | .arr σ τ => by
      apply OR.Hom.ext
      intro f
      apply OR.Hom.ext
      intro x
      rw [OR.projection_arr_apply, ← denote_MullerPsi σ, ← denote_MullerPsi τ]
      simp [MullerPsi, OR.denote_lam, OR.denote_app, OR.denote_closed, OR.denote_var, OR.lookup]

/-- Müller's `Ψ₁ M` and this repository's `Ψ¹ M` are observationally equivalent. -/
theorem MullerPsi_equiv {τ : OR.Ty} (M : OR.Tm [] τ) :
    ContextualOpEq (.app (MullerPsi τ) M) (.app (projectionTerm τ 1) M) := by
  apply (OR.full_abstraction_op_eq _ _).mpr
  apply OR.Hom.ext
  intro ρ
  simp only [OR.denote_app]
  have h := denote_MullerPsi τ
  simp only [OR.denoteClosed] at h
  rw [show ρ = PUnit.unit from rfl, h]
  rfl

/-! ## The hypothesis -/

/-- Every type of PCF is the translation of a Boolean type, so quantifying over Boolean
types below loses nothing. -/
theorem natTy_surjective : ∀ τ : OR.Ty, ∃ σ : Ty, natTy σ = τ
  | .nat => ⟨.B, rfl⟩
  | .arr a b => by
      obtain ⟨σ, rfl⟩ := natTy_surjective a
      obtain ⟨ρ, rfl⟩ := natTy_surjective b
      exact ⟨σ ⇒ ρ, rfl⟩

/-- Müller's Game Term Theorem (LMCS 8(4), 2012, Theorem 4.12) at grade 1, transcribed:
a finite term of grade 1 is observationally equivalent to a game term of grade 1. -/
def MullerGameTermTheorem : Prop :=
  ∀ (τ : Ty) (M : OR.Tm [] (natTy τ)),
    ContextualOpEq (.app (MullerPsi (natTy τ)) M) M →
      ∃ G : Game [] τ, ContextualOpEq G.toTm M

theorem _root_.OR.ContextualOpEq.trans {τ : OR.Ty} {A B C : OR.Tm [] τ}
    (h₁ : ContextualOpEq A B) (h₂ : ContextualOpEq B C) : ContextualOpEq A C :=
  (OR.full_abstraction_op_eq _ _).mpr
    (((OR.full_abstraction_op_eq _ _).mp h₁).trans ((OR.full_abstraction_op_eq _ _).mp h₂))

theorem _root_.OR.ContextualOpEq.symm {τ : OR.Ty} {A B : OR.Tm [] τ}
    (h : ContextualOpEq A B) : ContextualOpEq B A := ⟨h.2, h.1⟩

end OR.Sieber
