#!/usr/bin/env python3
"""Search for a finite same-world-vs-Kripke separation.

This is the next stage after search_sieber_counterexample.py.  It searches for
the *shape* of a Kripke failure rather than enumerating an order-4 truth table.

Mathematical target at an arrow σ→τ:
  ordinary:  F R-related at w iff for every a R-related at w,
             (F_i a_i)_i is R-related at w.
  Kripke:    additionally, for every reindexing phi:v→w and every a related
             at v, (F_{phi(i)} a_i)_i must be related at v.

Thus a separating witness is (R,w,v,phi,F,a) such that:
  (1) F passes all same-world argument tests at w;
  (2) a is related at v;
  (3) the reindexed application fails at v.

For prefix worlds, phi is the canonical projection/inclusion map used in the
O'Hearn--Riecke finite-world test.  Start with |w|=1, |v|=2, then 2→3.

TODO for Lean/Python follow-up:
  * import the exact finite-world relation generated by open Boolean PCF terms;
  * enumerate lower-order carrier elements from search_sieber_counterexample;
  * solve constraints (1)--(3);
  * minimise lexicographically by type order, |w|, |v|, relation arity/table size.

This file intentionally records the finite CSP specification before choosing a
solver, so a found witness can be independently checked.
"""

from dataclasses import dataclass
from typing import Tuple

@dataclass(frozen=True)
class WitnessShape:
    world: int
    extension: int
    # phi maps each coordinate of the extension back to a coordinate at world.
    phi: Tuple[int, ...]

def smallest_shapes():
    # General varying-arity shapes.  The prefix-context formalisation will
    # replace these by its exact induced coordinate maps.
    yield WitnessShape(1, 2, (0, 0))
    yield WitnessShape(2, 3, (0, 1, 1))
    yield WitnessShape(2, 3, (0, 0, 1))

if __name__ == "__main__":
    print("Kripke separation CSP shapes:")
    for s in smallest_shapes():
        print(s)
    print()
    print("Need F related at the source world for every same-world argument,")
    print("but one related argument at the extension whose reindexed application")
    print("is not related. This is the concrete quantifier gap to solve.")
